# Generated by Django 4.2.7 on 2023-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholars',
            field=models.ManyToManyField(blank=True, to='scholar.scholar', verbose_name='Bolsistas'),
        ),
    ]
