# Generated by Django 4.2.7 on 2023-12-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_alter_bank_options_alter_bankinginfo_options_and_more'),
        ('scholarship', '0002_alter_scholarship_scholars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'perfil de bolsa', 'verbose_name_plural': 'perfis de bolsas'},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.project'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholars',
            field=models.ManyToManyField(blank=True, to='scholar.scholar'),
        ),
    ]
