# Generated by Django 4.2.7 on 2023-11-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('scholar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scholar.scholar')),
            ],
            options={
                'verbose_name': 'coordenador',
                'verbose_name_plural': 'coordenadores',
            },
            bases=('scholar.scholar',),
        ),
    ]
