# Generated by Django 4.2.7 on 2023-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='is_coordinator',
            field=models.BooleanField(default=True, verbose_name='Coordenador'),
        ),
    ]
