# Generated by Django 4.2.7 on 2023-11-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_holder', '0002_alter_address_user_alter_bankinginfo_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshipholder',
            options={'verbose_name': 'bolsista', 'verbose_name_plural': 'bolsistas'},
        ),
    ]
