# Generated by Django 4.2.7 on 2023-11-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_alter_customuser_options_alter_scholar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
