# Generated by Django 4.2.7 on 2023-12-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_banks_seed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'banco', 'verbose_name_plural': 'bancos'},
        ),
        migrations.AlterModelOptions(
            name='bankinginfo',
            options={'verbose_name': 'dados bancários', 'verbose_name_plural': 'dados bancários'},
        ),
        migrations.AlterModelOptions(
            name='institutionalschedule',
            options={'verbose_name': 'horário institucional', 'verbose_name_plural': 'horários institucionais'},
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Número ou apt'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=250, verbose_name='logradouro'),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='número da conta'),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='agency_number',
            field=models.CharField(max_length=10, verbose_name='agência'),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholar.bank'),
        ),
        migrations.AlterField(
            model_name='bankinginfo',
            name='type',
            field=models.CharField(choices=[('CR', 'Corrente'), ('PP', 'Poupança')], max_length=2, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='institutionalschedule',
            name='week_day',
            field=models.CharField(choices=[('0', 'Segunda-Feira'), ('1', 'Terça-Feira'), ('2', 'Quarta-Feira'), ('3', 'Quinta-Feira'), ('4', 'Sexta-Feira'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=2, verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='birthday',
            field=models.DateField(verbose_name='data de nascimento'),
        ),
    ]
