# Generated by Django 4.2.7 on 2023-11-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.scholarship', verbose_name='Bolsa'),
        ),
    ]
