# Generated by Django 4.2.7 on 2023-11-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
        ('records', '0002_alter_record_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholar.scholar', verbose_name='Bolsista'),
        ),
    ]
