# Generated by Django 4.2.7 on 2023-12-20 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_alter_bank_options_alter_bankinginfo_options_and_more'),
        ('scholarship', '0003_alter_scholarship_options_alter_scholarship_project_and_more'),
        ('records', '0003_alter_record_scholar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'registro de atividade', 'verbose_name_plural': 'registros de atividades'},
        ),
        migrations.AddField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholar.scholar'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scholarship.scholarship'),
        ),
    ]
